import { defineConfig } from "vitepress"
import { groupIconMdPlugin, groupIconVitePlugin } from "vitepress-plugin-group-icons"

export default defineConfig({
    base: "/array/",
    description: "Functional utilities for arrays.",
    title: "array",
    markdown: {
        theme: {
            dark: "catppuccin-macchiato",
            light: "github-light-default",
        },
        config(md) {
            md.use(groupIconMdPlugin)
        },
    },
    themeConfig: {
        aside: false,
        outline: "deep",
        docFooter: {
            next: false,
            prev: false,
        },
        search: {
            provider: "local",
        },
        sidebar: [
            {
                base: "/Array/",
                text: "Array",
                items: [
                    { link: "create", text: "create" },
                    { link: "append", text: "append" },
                    { link: "at", text: "at" },
                    { link: "atOr", text: "atOr" },
                    { link: "atOrElse", text: "atOrElse" },
                    { link: "atOrThrow", text: "atOrThrow" },
                    { link: "clone", text: "clone" },
                    { link: "compact", text: "compact" },
                    { link: "concat", text: "concat" },
                    { link: "countBy", text: "countBy" },
                    { link: "drop", text: "drop" },
                    { link: "dropLast", text: "dropLast" },
                    { link: "every", text: "every" },
                    { link: "filter", text: "filter" },
                    { link: "find", text: "find" },
                    { link: "findIndex", text: "findIndex" },
                    { link: "findIndexOr", text: "findIndexOr" },
                    { link: "findIndexOrElse", text: "findIndexOrElse" },
                    { link: "findIndexOrThrow", text: "findIndexOrThrow" },
                    { link: "findLast", text: "findLast" },
                    { link: "findLastIndex", text: "findLastIndex" },
                    { link: "findLastIndexOr", text: "findLastIndexOr" },
                    { link: "findLastIndexOrElse", text: "findLastIndexOrElse" },
                    { link: "findLastIndexOrThrow", text: "findLastIndexOrThrow" },
                    { link: "findLastOr", text: "findLastOr" },
                    { link: "findLastOrElse", text: "findLastOrElse" },
                    { link: "findLastOrThrow", text: "findLastOrThrow" },
                    { link: "findMap", text: "findMap" },
                    { link: "findMapAll", text: "findMapAll" },
                    { link: "findMapLast", text: "findMapLast" },
                    { link: "findMapLastOr", text: "findMapLastOr" },
                    { link: "findMapLastOrElse", text: "findMapLastOrElse" },
                    { link: "findMapLastOrThrow", text: "findMapLastOrThrow" },
                    { link: "findMapOr", text: "findMapOr" },
                    { link: "findMapOrElse", text: "findMapOrElse" },
                    { link: "findMapOrThrow", text: "findMapOrThrow" },
                    { link: "findOr", text: "findOr" },
                    { link: "findOrElse", text: "findOrElse" },
                    { link: "findOrThrow", text: "findOrThrow" },
                    { link: "findRemove", text: "findRemove" },
                    { link: "findRemoveLast", text: "findRemoveLast" },
                    { link: "findRemoveLastOr", text: "findRemoveLastOr" },
                    { link: "findRemoveLastOrElse", text: "findRemoveLastOrElse" },
                    { link: "findRemoveLastOrThrow", text: "findRemoveLastOrThrow" },
                    { link: "findRemoveOr", text: "findRemoveOr" },
                    { link: "findRemoveOrElse", text: "findRemoveOrElse" },
                    { link: "findRemoveOrThrow", text: "findRemoveOrThrow" },
                    { link: "findReplace", text: "findReplace" },
                    { link: "findReplaceLast", text: "findReplaceLast" },
                    { link: "findReplaceLastOr", text: "findReplaceLastOr" },
                    { link: "findReplaceLastOrElse", text: "findReplaceLastOrElse" },
                    { link: "findReplaceLastOrThrow", text: "findReplaceLastOrThrow" },
                    { link: "findReplaceOr", text: "findReplaceOr" },
                    { link: "findReplaceOrElse", text: "findReplaceOrElse" },
                    { link: "findReplaceOrThrow", text: "findReplaceOrThrow" },
                    { link: "first", text: "first" },
                    { link: "firstOr", text: "firstOr" },
                    { link: "firstOrElse", text: "firstOrElse" },
                    { link: "firstOrThrow", text: "firstOrThrow" },
                    { link: "flatMap", text: "flatMap" },
                    { link: "forEach", text: "forEach" },
                    { link: "forEachRight", text: "forEachRight" },
                    { link: "groupBy", text: "groupBy" },
                    { link: "includes", text: "includes" },
                    { link: "includesAll", text: "includesAll" },
                    { link: "includesAny", text: "includesAny" },
                    { link: "includesNone", text: "includesNone" },
                    { link: "indexBy", text: "indexBy" },
                    { link: "indexOf", text: "indexOf" },
                    { link: "indexOfOr", text: "indexOfOr" },
                    { link: "indexOfOrElse", text: "indexOfOrElse" },
                    { link: "indexOfOrThrow", text: "indexOfOrThrow" },
                    { link: "insertAllAt", text: "insertAllAt" },
                    { link: "insertAllAtOr", text: "insertAllAtOr" },
                    { link: "insertAllAtOrElse", text: "insertAllAtOrElse" },
                    { link: "insertAllAtOrThrow", text: "insertAllAtOrThrow" },
                    { link: "insertAt", text: "insertAt" },
                    { link: "insertAtOr", text: "insertAtOr" },
                    { link: "insertAtOrElse", text: "insertAtOrElse" },
                    { link: "insertAtOrThrow", text: "insertAtOrThrow" },
                    { link: "is", text: "is" },
                    { link: "isEmpty", text: "isEmpty" },
                    { link: "isShallowEqual", text: "isShallowEqual" },
                    { link: "join", text: "join" },
                    { link: "last", text: "last" },
                    { link: "lastIndexOf", text: "lastIndexOf" },
                    { link: "lastIndexOfOr", text: "lastIndexOfOr" },
                    { link: "lastIndexOfOrElse", text: "lastIndexOfOrElse" },
                    { link: "lastIndexOfOrThrow", text: "lastIndexOfOrThrow" },
                    { link: "lastOr", text: "lastOr" },
                    { link: "lastOrElse", text: "lastOrElse" },
                    { link: "lastOrThrow", text: "lastOrThrow" },
                    { link: "length", text: "length" },
                    { link: "mapAt", text: "mapAt" },
                    { link: "mapAtOr", text: "mapAtOr" },
                    { link: "mapAtOrElse", text: "mapAtOrElse" },
                    { link: "mapAtOrThrow", text: "mapAtOrThrow" },
                    { link: "mapEach", text: "mapEach" },
                    { link: "maxOr", text: "maxOr" },
                    { link: "maxOrElse", text: "maxOrElse" },
                    { link: "maxOrThrow", text: "maxOrThrow" },
                    { link: "meanOr", text: "meanOr" },
                    { link: "meanOrElse", text: "meanOrElse" },
                    { link: "meanOrThrow", text: "meanOrThrow" },
                    { link: "medianOr", text: "medianOr" },
                    { link: "medianOrElse", text: "medianOrElse" },
                    { link: "medianOrThrow", text: "medianOrThrow" },
                    { link: "minOr", text: "minOr" },
                    { link: "minOrElse", text: "minOrElse" },
                    { link: "minOrThrow", text: "minOrThrow" },
                    { link: "none", text: "none" },
                    { link: "partition", text: "partition" },
                    { link: "prepend", text: "prepend" },
                    { link: "random", text: "random" },
                    { link: "randomOr", text: "randomOr" },
                    { link: "randomOrElse", text: "randomOrElse" },
                    { link: "reduce", text: "reduce" },
                    { link: "reject", text: "reject" },
                    { link: "remove", text: "remove" },
                    { link: "removeAll", text: "removeAll" },
                    { link: "removeAt", text: "removeAt" },
                    { link: "removeAtOr", text: "removeAtOr" },
                    { link: "removeAtOrElse", text: "removeAtOrElse" },
                    { link: "removeAtOrThrow", text: "removeAtOrThrow" },
                    { link: "removeLast", text: "removeLast" },
                    { link: "removeLastOr", text: "removeLastOr" },
                    { link: "removeLastOrElse", text: "removeLastOrElse" },
                    { link: "removeLastOrThrow", text: "removeLastOrThrow" },
                    { link: "removeOrElse", text: "removeOrElse" },
                    { link: "removeOrThrow", text: "removeOrThrow" },
                    { link: "replace", text: "replace" },
                    { link: "replaceLast", text: "replaceLast" },
                    { link: "replaceLastOr", text: "replaceLastOr" },
                    { link: "replaceLastOrElse", text: "replaceLastOrElse" },
                    { link: "replaceLastOrThrow", text: "replaceLastOrThrow" },
                    { link: "replaceOr", text: "replaceOr" },
                    { link: "replaceOrElse", text: "replaceOrElse" },
                    { link: "replaceOrThrow", text: "replaceOrThrow" },
                    { link: "setAt", text: "setAt" },
                    { link: "setAtOr", text: "setAtOr" },
                    { link: "setAtOrElse", text: "setAtOrElse" },
                    { link: "setAtOrThrow", text: "setAtOrThrow" },
                    { link: "shuffle", text: "shuffle" },
                    { link: "slice", text: "slice" },
                    { link: "some", text: "some" },
                    { link: "sort", text: "sort" },
                    { link: "sum", text: "sum" },
                    { link: "take", text: "take" },
                    { link: "takeLast", text: "takeLast" },
                    { link: "union", text: "union" },
                    { link: "unique", text: "unique" },
                ],
            },
        ],
        socialLinks: [
            { icon: "github", link: "https://github.com/MichaelOstermann/array" },
        ],
    },
    vite: {
        plugins: [
            groupIconVitePlugin(),
        ],
    },
})
